image: docker:latest

variables:
  REGISTRY: registry.gitlab.com
  IMAGE_NAME: radtriste/resume
  
  WEBSITE_URL: https://resume.tradisson.fr/
  
  STYLE_HTML: fedora.css
  STYLE_PDF: theme.yml 

  DIST_FOLDER: dist

stages:
- build docs
- docker
- prod

services:
  - docker:dind

.build:docs:
  stage: build docs
  before_script:
  - rm -rf $OUTPUT_DIR
  script:
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor -a stylesheet=/documents/themes/html/$STYLE_HTML -a icons -a toc2 -a toclevels=3 -a lang=$LANG -a website_url=$WEBSITE_URL -o /documents/$OUTPUT_DIR/index.html /documents/docs/index.adoc
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -a pdf-style=/documents/themes/pdf/$STYLE_PDF -a lang=$LANG -a website_url=$WEBSITE_URL -o /documents/$OUTPUT_DIR/radisson_resume.pdf /documents/docs/index.adoc
  - cp themes/html/asciidoctor.css $OUTPUT_DIR
  - cp -r docs/images/ $OUTPUT_DIR
  artifacts:
    paths:
    - "$OUTPUT_DIR"

build:docs:fr:
  extends: .build:docs
  variables:
    OUTPUT_DIR: "$DIST_FOLDER/fr"
    LANG: fr

build:docs:en:
  extends: .build:docs
  variables:
    OUTPUT_DIR: "$DIST_FOLDER/en"
    LANG: en
    
build:index:
  stage: build docs
  variables:
    OUTPUT_DIR: "$DIST_FOLDER/index"
  before_script:
  - rm -rf "$OUTPUT_DIR"
  script:
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor -a stylesheet=/documents/themes/html/$STYLE_HTML -a icons -o /documents/$OUTPUT_DIR/index.html /documents/index.adoc
  - cp themes/html/asciidoctor.css $OUTPUT_DIR
  - cp -r images/ $OUTPUT_DIR
  artifacts:
    paths:
    - "$OUTPUT_DIR"

build and push image:
  stage: docker
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  - echo "Commit sha = $CI_COMMIT_SHA"
  script:
  - docker build -t $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA .
  - docker push $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
  dependencies:
  - build:docs:fr
  - build:docs:en
  - build:index

tag_image:
  stage: prod
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  - echo "Commit sha = $CI_COMMIT_SHA"
  script:
  - docker pull $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA
  - docker tag $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHA $REGISTRY/$IMAGE_NAME:latest
  - docker push $REGISTRY/$IMAGE_NAME:latest
  only:
  - master