image: docker:latest

variables:
  REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: registry.gitlab.com/radtriste/resume
  
  WEBSITE_URL_FR: https://cv.tradisson.fr/
  WEBSITE_URL_EN: https://resume.tradisson.fr/
  
  PDF_FILE_FR: radisson_cv.pdf
  PDF_FILE_EN: radisson_resume.pdf
  
  STYLE_HTML: fedora.css
  STYLE_PDF: theme.yml 

  DIST_FOLDER: dist

stages:
- build
- deploy

services:
  - docker:dind

.build:image:
  stage: build
  variables:
    COMMON_ARGS: -a website_fr=$WEBSITE_URL_FR -a website_en=$WEBSITE_URL_EN
    COMMON_HTML_ARGS: -a stylesheet=/documents/themes/html/$STYLE_HTML -a icons -a toc2 -a toclevels=3
    COMMON_PDF_ARGS: -a pdf-style=/documents/themes/pdf/$STYLE_PDF 
  before_script:
  - rm -rf $OUTPUT_DIR
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  - echo "$IMAGE_NAME:$CI_COMMIT_SHA"
  script:
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor $COMMON_ARGS $COMMON_HTML_ARGS -a lang=$LANG -a website_prefix=$WEBSITE_URL -a pdfName=$PDF_FILE -o /documents/$OUTPUT_DIR/index.html /documents/index.adoc
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf $COMMON_ARGS $COMMON_PDF_ARGS -a lang=$LANG -a website_prefix=$WEBSITE_URL -o /documents/$OUTPUT_DIR/$PDF_FILE /documents/index.adoc
  - cp themes/html/asciidoctor.css $OUTPUT_DIR
  - cp -r images/ $OUTPUT_DIR
  - docker build --build-arg LANG=$LANG -t $IMAGE_NAME:$CI_COMMIT_SHA .
  - docker push $IMAGE_NAME:$CI_COMMIT_SHA

build:image:fr:
  extends: .build:image
  variables:
    LANG: fr
    OUTPUT_DIR: $DIST_FOLDER/fr
    WEBSITE_URL: $WEBSITE_URL_FR
    PDF_FILE: $PDF_FILE_FR
    IMAGE_NAME: $DOCKER_IMAGE/fr

build:image:en:
  extends: .build:image
  variables:
    LANG: en
    OUTPUT_DIR: $DIST_FOLDER/en
    WEBSITE_URL: $WEBSITE_URL_EN
    PDF_FILE: $PDF_FILE_EN
    IMAGE_NAME: $DOCKER_IMAGE/en


##################################################
## Deploy

.deploy:tag_image:
  stage: deploy
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  script:
  - docker pull $IMAGE_NAME:$CI_COMMIT_SHA
  - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:latest
  only:
  - master
  
deploy:tag_image:fr:
  extends: .deploy:tag_image
  variables:
    IMAGE_NAME: $DOCKER_IMAGE/fr
    
deploy:tag_image:en:
  extends: .deploy:tag_image
  variables:
    IMAGE_NAME: $DOCKER_IMAGE/en