image: docker:latest

variables:
  IMAGE_NAME: radtriste/resume

stages:
- build-docs
- build-docker

services:
  - docker:dind

build-docs:
  stage: build-docs
  before_script:
  - chmod u+x generate_with_docker.sh
  script:
  - ./generate_with_docker.sh

build-docker:
  stage: build-docker
  script:
    - docker build -t $IMAGE_NAME .
