image: docker:latest

variables:
  REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: registry.gitlab.com/radtriste/resume
  
  WEBSITE_URL_FR: https://cv.tradisson.fr/
  WEBSITE_URL_EN: https://resume.tradisson.fr/
  DIST_FOLDER: dist

stages:
- build
- deploy

services:
  - docker:dind

.build:image:
  stage: build   
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  - chmod u+x generate.sh
  script:
  - export GENERATION_COMMAND_PREFIX="docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor " && ./generate.sh
  - docker build --build-arg LANG=$GENERATION_LANG --build-arg DIST_FOLDER=$DIST_FOLDER -t $IMAGE_NAME:$CI_COMMIT_SHA .
  - docker push $IMAGE_NAME:$CI_COMMIT_SHA

build:image:fr:
  extends: .build:image
  variables:
    GENERATION_LANG: fr
    IMAGE_NAME: $DOCKER_IMAGE/fr

build:image:en:
  extends: .build:image
  variables:
    GENERATION_LANG: en
    IMAGE_NAME: $DOCKER_IMAGE/en


##################################################
## Deploy

.deploy:tag_image:
  stage: deploy
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  script:
  - docker pull $IMAGE_NAME:$CI_COMMIT_SHA
  - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:latest
  only:
  - master
  
deploy:tag_image:fr:
  extends: .deploy:tag_image
  variables:
    IMAGE_NAME: $DOCKER_IMAGE/fr
    
deploy:tag_image:en:
  extends: .deploy:tag_image
  variables:
    IMAGE_NAME: $DOCKER_IMAGE/en