version: '3.4'
services:
  resume:
    build:
      context: .
      args:
        LANG: en
        DIST_FOLDER: dist
    image: radtriste/resume/en:test
    ports:
      - "8080:80"
      
  cv:
    build:
      context: .
      args:
        LANG: fr
        DIST_FOLDER: dist
    image: radtriste/resume/fr:test
    ports:
      - "8081:80"