=== Principal Software Quality Engineer (since 2021)
[small]_Red Hat [Remote FR]_

**Business Automation Team - Kogito Serverless Workflow project** +
https://kogito.kie.org/ +
https://kiegroup.github.io/kogito-docs/serverlessworkflow/latest/index.html

* Contrôle qualité du projet Kogito Serverless Workflow et de ses releases via améliorations et maintenance
* Developpement et Tests des images Cloud
* Participation aux revues de code du projet global
* Travail en interne pour la mise en place du produit, basé sur le projet communataire

=== Senior Software Quality Engineer (2019-2021)
[small]_Red Hat [Remote FR]_

**Business Automation Team - Kogito project** +
https://kogito.kie.org/

* Mise en place de tests business-oriented (BDD) pour l'Operator Cloud du projet
* Mise en place complète de pipelines (nightly et release) d'automatisation pour le project entier (runtimes + images/operator cloud)
* Participation aux revues de code, principalement sur les parties Pipeline et Cloud
* Gestion des releases communautaires
* Travail en interne pour la mise en place du produit, basé sur le projet communataire