==== 2016: Software and Infrastructure Architect
Depuis Octobre 2016, Lebensversicherung von 1871 a.G. München, Munich [DE]

.Etude et réalisation en cours d’une migration des applications vers le Cloud

	Intégration de concepts Cloud dans l’architecture en place: Discovery, Configuration server, Gateway.
	Étude et mise en place d´un Cluster Kubernetes interne: IBM Cloud Private et Openshift.
	Ainsi que de technologies associées: Istio, Helm, Open Service Broker. 
	Mise en place de formations pour les développeurs.

.Intégration Continue/Déploiement continu (CI/CD)

	Développement de librairies partagées Jenkins (remote) et plugin Gradle (local). 
	Mise en place de pipelines Gitlab CI.

.Intégration du standard OAuth

	Installation du server OAuth RedHat Keycloak. 
	Interconnexions de Keycloak avec les 2 LDAPs de l´entreprise (Domino & Active Directory) et mise en place de Kerberos.

.Développement d’un projet de documentation
	
	Réalisation d’une architecture en microservices afin de collecter des informations sur les applications existantes : fichiers API Swagger, fichiers WSDL, interactions avec les autres applications, information sur l’application (découverte des applications effectuée par le système de Discovery mis en place). 
	Stockage des données dans différents systèmes: ElasticSearch, Neo4j, MySQL. 
	Développement d’une interface web pour visualiser toutes les informations collectées.
